version: "3.9"
services:
  casper-nctl:
    image: makesoftware/casper-nctl:v144-220303
    container_name: casper-nctl
    ports:
      # Opens RPC, REST and events ports on the host and service container
      - 11101:11101
      - 14101:14101
      - 18101:18101
    environment:
      - PREDEFINED_ACCOUNTS
      - MINIMUM_ROUND_EXPONENT
      - MAXIMUM_ROUND_EXPONENT
      - DEPLOY_DELAY
    volumes:
      - .casper-node:/home/casper/casper-node/utils/nctl/assets