[package]
name = "contract-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
casper-contract = { version = "1.4.3", default-features = false }
casper-types = "1.4.6"
base64 = "0.13.0"

[features]
default = [ "casper-contract/default", "casper-contract/std" ]