name: ci-casper-rust-contract

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"
      - "docs/**"

  pull_request:
    branches:
      - master
      - develop
      - feature/*
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204 # We use buildjet instead GH's free ubuntu-latest for faster builds
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - run: make prepare
      - run: make check-lint
      - run: make test
