name: ci-casper-js-client
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
      - develop
      - feature/*
    paths-ignore:
      - "**.md"

jobs:
  run-e2e:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      casper-nctl:
        # Docker Hub image
        image: makesoftware/casper-nctl:latest
        options: --name casper-nctl # -v ${{ github.workspace }}/assets:/home/casper/casper-node/utils/nctl/assets
        ports:
          # Opens RPC, REST and events ports on the host and service container
          - 11101:11101
          - 14101:14101
          - 18101:18101
        volumes:
          - /tmp:/home/casper/casper-node/utils/nctl/assets
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - run: sudo apt update && sudo apt install -y build-essential && sudo apt-get install wabt
      - run: make prepare
      - run: make build-contracts
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd client && npm install && sudo npm run e2e:reputation
        env:
          NODE_ENV: ci
          CHAIN_NAME: casper-net-1
          NODE_ADDRESS: http://localhost:11101/rpc
          EVENT_STREAM_ADDRESS: http://localhost:18101/events/main
          WASM_PATH: /target/wasm32-unknown-unknown/release/reputation_contract.wasm
          INSTALL_PAYMENT_AMOUNT: 200000000000
          DEPLOY_PAYMENT_AMOUNT: 200000000000
          NCTL_USERS_FOLDER_PATH: /tmp/net-1/users
