name: ci-casper-rust-contract

on:
  push:
    branches:
      - master
      - develop
      - final
    paths-ignore:
      - "**.md"
      - "docs/**"

  pull_request:
    branches:
      - master
      - develop
      - feature/*
      - final
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - run: make prepare
      - run: make test
