name: ci-casper-rust-contract

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - master
      - develop
      - feature/*
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CARGO_TARGET_DIR: /home/runner/work/dao-contracts/dao-contracts/target
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      - run: sudo apt update && sudo apt install -y build-essential
      - run: make prepare
      - run: make check-lint
      - run: make test
